repoURL: https://github.com/cbagade/argocd-all
targetRevision: code
environment: dev #this might come from top
argocd_vault_plugin:
  name: argocd-vault-plugin-helm-custom
cluster:
  url: https://kubernetes.default.svc
metadata:
  project: argo-learnings
  argocd_namespace: argocd
  nginx_app_namespace: nginx-ns
  helloworld_app_namespace: helloworld-ns
  node_app_namespace: nodeapp-ns
  certexpirycheck_namespace: certexpiry-ns
helloworld_app:
  label_from_app: label-at-apps
  label_from_cluster: cluster-label-at-apps #this might come from top
  replicas: 1