apiVersion: v1
kind: Service
metadata:
  name: py-service
  namespace: py-ns
  labels:
    app: py-app
spec:
  selector:
    app: py-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30005
  type: NodePort
